### PR TITLE
Add ContentType in S3 upload

### PR DESCRIPTION
**Pull request by Shauryadhaka**

### CODE REVIEW

**Comment by Shauryadhaka** [comment]
@aminalaee can we fast track this?

**Comment by Shauryadhaka** [comment]
@mmzeynalli @aminalaee Please review the PR.

**Review by aminalaee — APPROVED** [review]
Thank you for the contribution

**Comment by Shauryadhaka** [comment]
hey @aminalaee when will this pr be released? i saw even thou the code got merged there are no new versions yet!

**Comment by aminalaee** [comment]
I will release it today or tomorrow.

**Pull request merged**
